'use client';
import './admin.css';
import { useEffect, useState } from 'react';
import { Plus, Trash2, Package, ShoppingBag, Users, IndianRupee, ArrowLeft } from 'lucide-react';
import { defaultProducts, money, Product } from '../store';
const KEY='ecommerce-products-v1';
export default function Admin(){
 const [products,setProducts]=useState<Product[]>(defaultProducts);const [show,setShow]=useState(false);const [form,setForm]=useState({name:'',category:'Electronics',price:'',stock:'',emoji:'📦',description:''});
 useEffect(()=>{const saved=localStorage.getItem(KEY);if(saved)try{setProducts(JSON.parse(saved))}catch{}},[]);
 const save=(next:Product[])=>{setProducts(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const add=()=>{if(!form.name||!form.price)return;save([...products,{id:`p-${Date.now()}`,name:form.name,category:form.category,price:Number(form.price),stock:Number(form.stock)||0,emoji:form.emoji||'📦',description:form.description||'New product'}]);setForm({name:'',category:'Electronics',price:'',stock:'',emoji:'📦',description:''});setShow(false)};
 return <div className="admin"><header className="admin-head"><a href="/"><ArrowLeft size={18}/> Store</a><strong>ECOMMERCE ADMIN</strong><span>Administrator</span></header><main className="admin-main"><div className="admin-title"><div><h1>Dashboard</h1><p>Manage your store products and inventory.</p></div><button className="primary" onClick={()=>setShow(true)}><Plus size={18}/> Add product</button></div><div className="stats"><div><Package/><small>Products</small><strong>{products.length}</strong></div><div><ShoppingBag/><small>Orders</small><strong>0</strong></div><div><Users/><small>Customers</small><strong>0</strong></div><div><IndianRupee/><small>Catalog value</small><strong>{money(products.reduce((s,p)=>s+p.price,0))}</strong></div></div><section className="admin-card"><div className="admin-card-head"><h2>Products</h2><span>{products.length} total</span></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Action</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><span className="admin-product">{p.emoji}</span><strong>{p.name}</strong></td><td>{p.category}</td><td>{money(p.price)}</td><td><span className={p.stock<5?'low':'stock'}>{p.stock}</span></td><td><button className="delete" onClick={()=>save(products.filter(x=>x.id!==p.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></section></main>{show&&<div className="modal-bg"><div className="modal"><h2>Add product</h2><div className="form-grid"><label>Product name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Electronics</option><option>Fashion</option><option>Home & Living</option><option>Accessories</option></select></label><label>Price<input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Stock<input type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label>Icon<input value={form.emoji} onChange={e=>setForm({...form,emoji:e.target.value})}/></label><label>Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="modal-actions"><button onClick={()=>setShow(false)}>Cancel</button><button className="primary" onClick={add}>Save product</button></div></div></div>}</div>}
